# Generated by Django 3.1.4 on 2020-12-14 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('team_leader', models.CharField(max_length=200)),
                ('clock_in', models.DateTimeField(default=datetime.datetime(2020, 12, 14, 23, 14, 30, 749275, tzinfo=utc), editable=False)),
                ('work_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Work_logs',
        ),
    ]
