# Generated by Django 3.1.4 on 2020-12-14 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201214_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130974', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='work_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 15, 17, 41, 314568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='work_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 15, 17, 41, 314614, tzinfo=utc)),
        ),
    ]
