# Generated by Django 3.1.4 on 2020-12-14 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20201214_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130610', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='work_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 15, 50, 45, 161262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='work_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 15, 50, 45, 161307, tzinfo=utc)),
        ),
    ]
