# Generated by Django 3.1.4 on 2020-12-14 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20201214_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_profile',
            name='team_leader',
            field=models.CharField(default='Senior', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130519', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='work_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 16, 30, 5, 432769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='work_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 16, 30, 5, 432818, tzinfo=utc)),
        ),
    ]
