# Generated by Django 3.1.4 on 2020-12-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20201214_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130483', max_length=10, null=True),
        ),
    ]
