# Generated by Django 3.1.4 on 2020-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20201216_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130228', max_length=10, null=True),
        ),
    ]
