# Generated by Django 3.1.4 on 2020-12-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20201216_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130274', max_length=10, null=True),
        ),
    ]
