# Generated by Django 3.1.4 on 2020-12-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20201221_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130207', max_length=10, null=True),
        ),
    ]
