# Generated by Django 3.1.4 on 2020-12-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_auto_20201222_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130212', max_length=10, null=True),
        ),
    ]
