# Generated by Django 3.1.4 on 2020-12-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_auto_20201223_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130765', max_length=10, null=True),
        ),
    ]
