# Generated by Django 3.1.4 on 2020-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0037_auto_20201224_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='ANC130423', max_length=10, null=True),
        ),
    ]
