# Generated by Django 3.1.4 on 2020-12-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
