# Generated by Django 3.1.4 on 2020-12-24 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0003_auto_20201223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='clock_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 24, 0, 0, 28, 959279), null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='team_leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='work_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='work_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
