# Generated by Django 3.1.4 on 2020-12-24 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0004_auto_20201224_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 24, 1, 23, 34, 720202)),
        ),
        migrations.AlterField(
            model_name='logger',
            name='work_id',
            field=models.CharField(default='WORK130_994_TAG', max_length=20),
        ),
    ]
