# Generated by Django 3.1.4 on 2020-12-30 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0005_auto_20201224_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 30, 11, 21, 22, 266378)),
        ),
        migrations.AlterField(
            model_name='logger',
            name='work_id',
            field=models.CharField(default='WORK130_383_TAG', max_length=20),
        ),
    ]
