# Generated by Django 3.1.4 on 2020-12-16 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('team_leader', models.CharField(max_length=200)),
                ('clock_in', models.DateTimeField(default=datetime.datetime(2020, 12, 16, 0, 49, 17, 443087, tzinfo=utc))),
                ('work_title', models.CharField(max_length=200)),
            ],
        ),
    ]
