# Generated by Django 3.1.4 on 2020-12-16 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_auto_20201216_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 11, 46, 8, 423676, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
