# Generated by Django 3.1.4 on 2020-12-16 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_auto_20201216_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='id',
            new_name='attendance_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 12, 6, 41, 312806, tzinfo=utc)),
        ),
    ]
