# Generated by Django 3.1.4 on 2020-12-16 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_auto_20201216_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 22, 34, 0, 290361, tzinfo=utc)),
        ),
    ]
