# Generated by Django 3.1.4 on 2020-12-20 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0007_auto_20201216_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 16, 12, 32, 211216)),
        ),
    ]
