# Generated by Django 3.1.4 on 2020-12-21 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_auto_20201220_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 1, 12, 8, 763252)),
        ),
    ]
