# Generated by Django 3.1.4 on 2020-12-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0009_auto_20201221_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
