# Generated by Django 3.1.4 on 2020-12-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_auto_20201221_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
    ]
